import postgres from 'postgres';
import bcryptjs from 'bcryptjs';

// ─── Client bootstrap ───────────────────────────────────────────────────────
// Supabase Postgres. Set SUPABASE_DB_URL to the "Transaction pooler" URI from
// Supabase → Project Settings → Database → Connection string (port 6543),
// e.g. postgresql://postgres.<ref>:<password>@aws-0-<region>.pooler.supabase.com:6543/postgres
// DATABASE_URL is honored as a fallback name.
const url = process.env.SUPABASE_DB_URL || process.env.DATABASE_URL || '';
if (!url) {
  console.warn('[db] SUPABASE_DB_URL is not set — database features will fail. See ENVIRONMENT.md.');
}

const client = postgres(url, {
  ssl: 'require',
  max: 3,
  idle_timeout: 20,
  // Fail fast: a hung connect must surface as a JSON error well inside the
  // function budget, never stack up into a platform timeout.
  connect_timeout: 8,
  // Required for Supabase's transaction pooler (no prepared statements).
  prepare: false,
  // Parse Postgres bigints (COUNT(*), IDENTITY ids) as JS numbers — our data
  // volumes are far below Number.MAX_SAFE_INTEGER.
  types: {
    bigint: { to: 20, from: [20], parse: (x: string) => Number(x), serialize: (x: unknown) => String(x) },
  },
});

// Translate legacy '?' placeholders (SQLite style, used throughout the app)
// to Postgres $1..$n.
function toPg(sqlText: string): string {
  let i = 0;
  return sqlText.replace(/\?/g, () => `$${++i}`);
}

// ─── Lazy schema init ───────────────────────────────────────────────────────
// Bump when the DDL below changes — instances skip ALL migration work when the
// stored version matches, so cold starts cost one cheap SELECT instead of a
// DDL storm. Concurrent cold starts used to run the full migration in
// parallel and deadlock each other on table locks (observed as 60s platform
// timeouts on every route the moment several functions booted together).
const SCHEMA_VERSION = '2026-09-09.1';

let initPromise: Promise<void> | null = null;

function init(): Promise<void> {
  if (!initPromise) {
    // A failed init must not be cached forever — let the next request retry.
    initPromise = runInit().catch((e) => {
      initPromise = null;
      throw e;
    });
  }
  return initPromise;
}

async function runInit(): Promise<void> {
  // Fast path: schema already migrated by an earlier boot.
  try {
    const row = await client.unsafe(
      "SELECT value FROM settings WHERE key = 'schema_version'"
    );
    if ((row[0] as unknown as { value?: string })?.value === SCHEMA_VERSION) return;
  } catch {
    /* settings table missing → first-ever boot, run the full init */
  }

  // No advisory lock here: session locks are unsafe through the transaction
  // pooler. Every migration statement is idempotent, and after the sentinel
  // is written this path can never run again, so a one-time concurrent
  // migration race is acceptable (a loser just errors and retries into the
  // fast path).
  await migrate();
  await client.unsafe(
    `INSERT INTO settings (key, value) VALUES ('schema_version', $1)
     ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_at = now()`,
    [SCHEMA_VERSION]
  );
}

async function migrate(): Promise<void> {
  {
    await client.unsafe(`
      CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT DEFAULT 'user',
        status TEXT DEFAULT 'active' CHECK (status IN ('active', 'blocked')),
        avatar_url TEXT,
        created_at TIMESTAMPTZ DEFAULT now(),
        last_login TIMESTAMPTZ
      );
      CREATE TABLE IF NOT EXISTS feedback (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
        user_name TEXT,
        type TEXT NOT NULL CHECK (type IN ('bug', 'suggestion', 'improvement')),
        title TEXT NOT NULL,
        message TEXT NOT NULL,
        status TEXT DEFAULT 'new' CHECK (status IN ('new', 'reviewing', 'resolved', 'dismissed')),
        admin_note TEXT,
        created_at TIMESTAMPTZ DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS activity_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
        user_name TEXT,
        action TEXT NOT NULL,
        details TEXT,
        ip_address TEXT,
        created_at TIMESTAMPTZ DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS settings (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL,
        updated_at TIMESTAMPTZ DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS usage_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
        user_name TEXT,
        model TEXT NOT NULL,
        input_type TEXT DEFAULT 'text',
        duration_ms INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS user_api_keys (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
        user_name TEXT,
        provider TEXT NOT NULL,
        api_key TEXT NOT NULL,
        base_url TEXT,
        model TEXT,
        created_at TIMESTAMPTZ DEFAULT now(),
        UNIQUE (user_id, provider)
      );
      CREATE TABLE IF NOT EXISTS media_credits (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
        user_name TEXT,
        model_id TEXT,
        kind TEXT,
        cost INTEGER NOT NULL DEFAULT 1,
        created_at TIMESTAMPTZ DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS gallery_images (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
        user_name TEXT,
        url TEXT NOT NULL,
        prompt TEXT,
        platform TEXT,
        model TEXT,
        aspect_ratio TEXT,
        created_at TIMESTAMPTZ DEFAULT now()
      );
      -- Idempotent column migrations
      ALTER TABLE users ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
      ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_provider TEXT DEFAULT 'password';
      ALTER TABLE feedback ADD COLUMN IF NOT EXISTS admin_responded_at TIMESTAMPTZ;
      ALTER TABLE feedback ADD COLUMN IF NOT EXISTS user_viewed_at TIMESTAMPTZ;
      -- Denormalized user_name so rows are readable directly in the dashboard
      ALTER TABLE usage_log ADD COLUMN IF NOT EXISTS user_name TEXT;
      ALTER TABLE activity_log ADD COLUMN IF NOT EXISTS user_name TEXT;
      ALTER TABLE gallery_images ADD COLUMN IF NOT EXISTS user_name TEXT;
      ALTER TABLE feedback ADD COLUMN IF NOT EXISTS user_name TEXT;
      -- Lock down Supabase's auto-generated Data API (PostgREST): RLS with no
      -- policies = deny-by-default for anon/authenticated API access. Our own
      -- direct Postgres connection owns the tables and is unaffected.
      ALTER TABLE users ENABLE ROW LEVEL SECURITY;
      ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;
      ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;
      ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
      ALTER TABLE usage_log ENABLE ROW LEVEL SECURITY;
      ALTER TABLE gallery_images ENABLE ROW LEVEL SECURITY;
      ALTER TABLE media_credits ENABLE ROW LEVEL SECURITY;
      ALTER TABLE user_api_keys ENABLE ROW LEVEL SECURITY;
    `);

    // Backfill user_name on rows created before the column existed.
    await client.unsafe(`
      UPDATE usage_log t SET user_name = u.name FROM users u WHERE t.user_id = u.id AND t.user_name IS NULL;
      UPDATE activity_log t SET user_name = u.name FROM users u WHERE t.user_id = u.id AND t.user_name IS NULL;
      UPDATE gallery_images t SET user_name = u.name FROM users u WHERE t.user_id = u.id AND t.user_name IS NULL;
      UPDATE feedback t SET user_name = u.name FROM users u WHERE t.user_id = u.id AND t.user_name IS NULL;
    `);

    await pruneLogs();
    await seedSettings();
    await seedAdmin();
  }
}

// Retention: keep only the last 7 days AND at most the newest 200 rows in the
// high-churn log tables. Runs on every cold start (init) — cheap and frequent
// enough for this app's volume.
async function pruneLogs(): Promise<void> {
  try {
    await client.unsafe(`
      DELETE FROM usage_log WHERE created_at < now() - interval '7 days'
        OR id NOT IN (SELECT id FROM usage_log ORDER BY id DESC LIMIT 200);
      DELETE FROM activity_log WHERE created_at < now() - interval '7 days'
        OR id NOT IN (SELECT id FROM activity_log ORDER BY id DESC LIMIT 200);
      DELETE FROM media_credits WHERE created_at < now() - interval '7 days';
    `);
  } catch (e) {
    console.warn('[db] log pruning failed (non-fatal):', e);
  }
}

async function seedSettings(): Promise<void> {
  const defaults: Record<string, string> = {
    rate_limit_max: '20',
    rate_limit_window_minutes: '60',
    min_password_length: '6',
    maintenance_mode: 'false',
    maintenance_message: '',
    default_model: 'googleai/gemini-2.5-flash',
    allow_registration: 'true',
    announcement_active: 'false',
    announcement_text: '',
    announcement_type: 'info',
  };
  // One multi-row insert — ten sequential round trips on every cold start
  // were a meaningful slice of the ~10s function budget.
  const entries = Object.entries(defaults);
  const values: string[] = [];
  const params: string[] = [];
  entries.forEach(([key, value], i) => {
    values.push(`($${i * 2 + 1}, $${i * 2 + 2})`);
    params.push(key, value);
  });
  await client.unsafe(
    `INSERT INTO settings (key, value) VALUES ${values.join(', ')} ON CONFLICT (key) DO NOTHING`,
    params
  );
}

async function seedAdmin(): Promise<void> {
  const rows = await client.unsafe('SELECT COUNT(*) AS count FROM users');
  const count = Number((rows[0] as unknown as { count: number | string })?.count ?? 0);
  if (count === 0) {
    const hash = bcryptjs.hashSync('Admin@123', 10);
    await client.unsafe(
      'INSERT INTO users (name, email, password_hash, role, status) VALUES ($1, $2, $3, $4, $5)',
      ['Admin', 'admin@promptstudio.ai', hash, 'admin', 'active']
    );
    // eslint-disable-next-line no-console
    console.log('Default admin user created: admin@promptstudio.ai');
  }
}

// ─── Query helpers ──────────────────────────────────────────────────────────
// Same API the app has always used; '?' placeholders are translated to $n.

export type DbValue = string | number | boolean | null | undefined;

export async function queryRows<T>(sql: string, ...args: DbValue[]): Promise<T[]> {
  await init();
  const rows = await client.unsafe(toPg(sql), args as never[]);
  return rows as unknown as T[];
}

export async function queryRow<T>(sql: string, ...args: DbValue[]): Promise<T | null> {
  const rows = await queryRows<T>(sql, ...args);
  return rows[0] ?? null;
}

// Tables with an auto-generated id — INSERTs into these get RETURNING id
// appended automatically so exec() can report lastInsertRowid like before.
const ID_TABLE_INSERT = /^\s*insert\s+into\s+(users|feedback|activity_log|usage_log|gallery_images|media_credits)\b/i;

export async function exec(
  sql: string,
  ...args: DbValue[]
): Promise<{ changes: number; lastInsertRowid: bigint | undefined }> {
  await init();
  let text = toPg(sql);
  const wantId = ID_TABLE_INSERT.test(text) && !/returning/i.test(text);
  if (wantId) text += ' RETURNING id';
  const rows = await client.unsafe(text, args as never[]);
  const id = wantId && rows[0] != null ? (rows[0] as { id?: number | bigint }).id : undefined;
  return {
    changes: (rows as unknown as { count?: number }).count ?? rows.length,
    lastInsertRowid: id === undefined || id === null ? undefined : BigInt(id),
  };
}

// Escape hatch for dynamic queries (args use $1..$n or none).
export async function execute(sql: string, args: DbValue[] = []) {
  await init();
  return client.unsafe(toPg(sql), args as never[]);
}

// Rare callers that want the raw postgres.js client.
export async function getClient() {
  await init();
  return client;
}

const db = { queryRows, queryRow, exec, execute, getClient };
export default db;
