import postgres from 'postgres';
import bcryptjs from 'bcryptjs';

// ─── Client bootstrap ───────────────────────────────────────────────────────
// Supabase Postgres. Set SUPABASE_DB_URL to the "Transaction pooler" URI from
// Supabase → Project Settings → Database → Connection string (port 6543),
// e.g. postgresql://postgres.<ref>:<password>@aws-0-<region>.pooler.supabase.com:6543/postgres
// DATABASE_URL is honored as a fallback name.
const url = process.env.SUPABASE_DB_URL || process.env.DATABASE_URL || '';
if (!url) {
  console.warn('[db] SUPABASE_DB_URL is not set — database features will fail. See ENVIRONMENT.md.');
}

const client = postgres(url, {
  ssl: 'require',
  max: 3,
  idle_timeout: 20,
  connect_timeout: 15,
  // Required for Supabase's transaction pooler (no prepared statements).
  prepare: false,
  // Parse Postgres bigints (COUNT(*), IDENTITY ids) as JS numbers — our data
  // volumes are far below Number.MAX_SAFE_INTEGER.
  types: {
    bigint: { to: 20, from: [20], parse: (x: string) => Number(x), serialize: (x: unknown) => String(x) },
  },
});

// Translate legacy '?' placeholders (SQLite style, used throughout the app)
// to Postgres $1..$n.
function toPg(sqlText: string): string {
  let i = 0;
  return sqlText.replace(/\?/g, () => `$${++i}`);
}

// ─── Lazy schema init ───────────────────────────────────────────────────────
let initPromise: Promise<void> | null = null;

async function init(): Promise<void> {
  if (initPromise) return initPromise;
  initPromise = (async () => {
    await client.unsafe(`
      CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        role TEXT DEFAULT 'user',
        status TEXT DEFAULT 'active' CHECK (status IN ('active', 'blocked')),
        avatar_url TEXT,
        created_at TIMESTAMPTZ DEFAULT now(),
        last_login TIMESTAMPTZ
      );
      CREATE TABLE IF NOT EXISTS feedback (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
        type TEXT NOT NULL CHECK (type IN ('bug', 'suggestion', 'improvement')),
        title TEXT NOT NULL,
        message TEXT NOT NULL,
        status TEXT DEFAULT 'new' CHECK (status IN ('new', 'reviewing', 'resolved', 'dismissed')),
        admin_note TEXT,
        created_at TIMESTAMPTZ DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS activity_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
        action TEXT NOT NULL,
        details TEXT,
        ip_address TEXT,
        created_at TIMESTAMPTZ DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS settings (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL,
        updated_at TIMESTAMPTZ DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS usage_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
        model TEXT NOT NULL,
        input_type TEXT DEFAULT 'text',
        duration_ms INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT now()
      );
      CREATE TABLE IF NOT EXISTS gallery_images (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
        url TEXT NOT NULL,
        prompt TEXT,
        platform TEXT,
        model TEXT,
        aspect_ratio TEXT,
        created_at TIMESTAMPTZ DEFAULT now()
      );
      -- Idempotent column migrations
      ALTER TABLE users ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';
      ALTER TABLE feedback ADD COLUMN IF NOT EXISTS admin_responded_at TIMESTAMPTZ;
      ALTER TABLE feedback ADD COLUMN IF NOT EXISTS user_viewed_at TIMESTAMPTZ;
    `);

    await seedSettings();
    await seedAdmin();
  })();
  return initPromise;
}

async function seedSettings(): Promise<void> {
  const defaults: Record<string, string> = {
    rate_limit_max: '20',
    rate_limit_window_minutes: '60',
    min_password_length: '6',
    maintenance_mode: 'false',
    maintenance_message: '',
    default_model: 'googleai/gemini-2.5-flash',
    allow_registration: 'true',
    announcement_active: 'false',
    announcement_text: '',
    announcement_type: 'info',
  };
  for (const [key, value] of Object.entries(defaults)) {
    await client.unsafe(
      'INSERT INTO settings (key, value) VALUES ($1, $2) ON CONFLICT (key) DO NOTHING',
      [key, value]
    );
  }
}

async function seedAdmin(): Promise<void> {
  const rows = await client.unsafe('SELECT COUNT(*) AS count FROM users');
  const count = Number((rows[0] as unknown as { count: number | string })?.count ?? 0);
  if (count === 0) {
    const hash = bcryptjs.hashSync('Admin@123', 10);
    await client.unsafe(
      'INSERT INTO users (name, email, password_hash, role, status) VALUES ($1, $2, $3, $4, $5)',
      ['Admin', 'admin@promptstudio.ai', hash, 'admin', 'active']
    );
    // eslint-disable-next-line no-console
    console.log('Default admin user created: admin@promptstudio.ai');
  }
}

// ─── Query helpers ──────────────────────────────────────────────────────────
// Same API the app has always used; '?' placeholders are translated to $n.

export type DbValue = string | number | boolean | null | undefined;

export async function queryRows<T>(sql: string, ...args: DbValue[]): Promise<T[]> {
  await init();
  const rows = await client.unsafe(toPg(sql), args as never[]);
  return rows as unknown as T[];
}

export async function queryRow<T>(sql: string, ...args: DbValue[]): Promise<T | null> {
  const rows = await queryRows<T>(sql, ...args);
  return rows[0] ?? null;
}

// Tables with an auto-generated id — INSERTs into these get RETURNING id
// appended automatically so exec() can report lastInsertRowid like before.
const ID_TABLE_INSERT = /^\s*insert\s+into\s+(users|feedback|activity_log|usage_log|gallery_images)\b/i;

export async function exec(
  sql: string,
  ...args: DbValue[]
): Promise<{ changes: number; lastInsertRowid: bigint | undefined }> {
  await init();
  let text = toPg(sql);
  const wantId = ID_TABLE_INSERT.test(text) && !/returning/i.test(text);
  if (wantId) text += ' RETURNING id';
  const rows = await client.unsafe(text, args as never[]);
  const id = wantId && rows[0] != null ? (rows[0] as { id?: number | bigint }).id : undefined;
  return {
    changes: (rows as unknown as { count?: number }).count ?? rows.length,
    lastInsertRowid: id === undefined || id === null ? undefined : BigInt(id),
  };
}

// Escape hatch for dynamic queries (args use $1..$n or none).
export async function execute(sql: string, args: DbValue[] = []) {
  await init();
  return client.unsafe(toPg(sql), args as never[]);
}

// Rare callers that want the raw postgres.js client.
export async function getClient() {
  await init();
  return client;
}

const db = { queryRows, queryRow, exec, execute, getClient };
export default db;
