-- One-time migration: rebuild log/feedback/gallery tables so user_name sits
-- right after user_id (Postgres cannot reorder columns in place).
-- Run in Supabase → SQL Editor. Safe for small tables; runs in a transaction.
-- Fresh databases created by the app already use this order — this script is
-- only for databases created before July 19, 2026.

BEGIN;

-- ── usage_log ───────────────────────────────────────────────────────────────
CREATE TABLE usage_log_new (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  user_name TEXT,
  model TEXT NOT NULL,
  input_type TEXT DEFAULT 'text',
  duration_ms INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);
INSERT INTO usage_log_new (id, user_id, user_name, model, input_type, duration_ms, created_at)
  SELECT id, user_id, user_name, model, input_type, duration_ms, created_at FROM usage_log;
DROP TABLE usage_log;
ALTER TABLE usage_log_new RENAME TO usage_log;
SELECT setval(pg_get_serial_sequence('usage_log', 'id'), COALESCE((SELECT MAX(id) FROM usage_log), 0) + 1, false);
ALTER TABLE usage_log ENABLE ROW LEVEL SECURITY;

-- ── activity_log ────────────────────────────────────────────────────────────
CREATE TABLE activity_log_new (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  user_name TEXT,
  action TEXT NOT NULL,
  details TEXT,
  ip_address TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);
INSERT INTO activity_log_new (id, user_id, user_name, action, details, ip_address, created_at)
  SELECT id, user_id, user_name, action, details, ip_address, created_at FROM activity_log;
DROP TABLE activity_log;
ALTER TABLE activity_log_new RENAME TO activity_log;
SELECT setval(pg_get_serial_sequence('activity_log', 'id'), COALESCE((SELECT MAX(id) FROM activity_log), 0) + 1, false);
ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;

-- ── gallery_images ──────────────────────────────────────────────────────────
CREATE TABLE gallery_images_new (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  user_name TEXT,
  url TEXT NOT NULL,
  prompt TEXT,
  platform TEXT,
  model TEXT,
  aspect_ratio TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);
INSERT INTO gallery_images_new (id, user_id, user_name, url, prompt, platform, model, aspect_ratio, created_at)
  SELECT id, user_id, user_name, url, prompt, platform, model, aspect_ratio, created_at FROM gallery_images;
DROP TABLE gallery_images;
ALTER TABLE gallery_images_new RENAME TO gallery_images;
SELECT setval(pg_get_serial_sequence('gallery_images', 'id'), COALESCE((SELECT MAX(id) FROM gallery_images), 0) + 1, false);
ALTER TABLE gallery_images ENABLE ROW LEVEL SECURITY;

-- ── feedback ────────────────────────────────────────────────────────────────
CREATE TABLE feedback_new (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  user_name TEXT,
  type TEXT NOT NULL CHECK (type IN ('bug', 'suggestion', 'improvement')),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT DEFAULT 'new' CHECK (status IN ('new', 'reviewing', 'resolved', 'dismissed')),
  admin_note TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  admin_responded_at TIMESTAMPTZ,
  user_viewed_at TIMESTAMPTZ
);
INSERT INTO feedback_new (id, user_id, user_name, type, title, message, status, admin_note, created_at, admin_responded_at, user_viewed_at)
  SELECT id, user_id, user_name, type, title, message, status, admin_note, created_at, admin_responded_at, user_viewed_at FROM feedback;
DROP TABLE feedback;
ALTER TABLE feedback_new RENAME TO feedback;
SELECT setval(pg_get_serial_sequence('feedback', 'id'), COALESCE((SELECT MAX(id) FROM feedback), 0) + 1, false);
ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;

COMMIT;
